version: '3'
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.dev
      args:
        UID: ${USER_ID:-1000}
        GID: ${GROUP_ID:-1000}
    ports:
      - "10000:10000"
    volumes:
      - ./gateway:/workspace
      - web-dist:/dist 

  langchain:
    build:
      context: ./langchain
      dockerfile: Dockerfile.dev
      args:
        UID: ${USER_ID:-1000}
        GID: ${GROUP_ID:-1000}
    volumes:
      - ./langchain:/workspace

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
      args:
        UID: ${USER_ID:-1000}
        GID: ${GROUP_ID:-1000}
    volumes:
      - ./web:/workspace
      - web-dist:/workspace/dist 

volumes:
  web-dist: