version: '3'
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.prod
    ports:
      - "10000:10000"
    volumes:
      - web-dist:/dist 
    depends_on:
      - web

  langchain:
    build:
      context: ./langchain
      dockerfile: Dockerfile.prod

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    volumes:
      - web-dist:/workspace/dist 

volumes:
  web-dist: