FROM ubuntu:22.04 as builder

RUN apt-get update && \
    apt-get install -y curl build-essential gcc make pkg-config libssl-dev

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /workspace

COPY . .

RUN cargo build --release

CMD ["./target/release/gateway"]

FROM ubuntu:22.04 as runtime

RUN apt-get update && \
    apt-get install -y libssl-dev

COPY --from=builder /workspace/target/release/gateway /gateway

CMD ["/gateway"]