FROM python:3.10

WORKDIR /workspace

COPY pyproject.toml poetry.lock* /workspace/

RUN pip install poetry \
    && poetry config virtualenvs.create false

RUN poetry install

COPY setup-user.sh /setup-user.sh

RUN chmod +x /setup-user.sh && /setup-user.sh

ARG UID
USER ${UID}

COPY . /workspace

CMD ["python3", "bootstrap_dev.py"]
