dev:
    STAGE_NAME=dev RUST_LOG=http_api=debug cargo lambda watch --package http-api

build:
    cargo lambda build --arm64 --release

deploy  STAGE_NAME: build
    cargo lambda deploy --binary-name http-api "{{STAGE_NAME}}-46ki75-internal-lambda-function-http-api"

test:
    cargo test --lib
