build: 
    cargo lambda build --release

deploy  STAGE_NAME: build
    cargo lambda deploy --binary-name notion-notification "{{STAGE_NAME}}-46ki75-internal-lambda-function-notion-notification"

test:
    cargo test --lib

invoke:
    STAGE_NAME=dev FUNCTION_NAME=notion-notification ./scripts/invoke.sh
