dev: 
    STAGE_NAME=dev RUST_LOG=internal_graphql=debug cargo lambda watch --package internal-graphql

build: 
    cargo lambda build --arm64 --release

deploy  STAGE_NAME: build
    cargo lambda deploy --binary-name internal-graphql "{{STAGE_NAME}}-46ki75-internal-lambda-function-graphql"

test:
    cargo test --lib
