dev: 
    cargo lambda watch -p 20010

build: 
    cargo lambda build --release

deploy: build
    zip ../../target/lambda/graphql/bootstrap.zip ../../target/lambda/graphql/bootstrap
    aws lambda update-function-code --function-name "${ENVIRONMENT}-46ki75-lambda-function-graphql" --zip-file fileb://../../target/lambda/graphql/bootstrap.zip 1>/dev/null